version: "3"
services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:rabbit

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
